// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Beacon",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Beacon",
            targets: ["AppModule"],
            bundleIdentifier: "com.algotyrnt.Beacon",
            teamIdentifier: "V2F9G4736H",
            displayVersion: "1.3",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                 .portrait,
                 .landscapeRight(.when(deviceFamilies: [.pad])),
                 .landscapeLeft(.when(deviceFamilies: [.pad])),
                 .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .bluetoothAlways(purposeString: "Bluetooth allows Beacon to form an offline emergency network with nearby devices."),
                .localNetwork(purposeString: "Local network access enables Beacon to share emergency data with nearby devices.", bonjourServiceTypes: ["_beacon-mesh._tcp", "_beacon-mesh._udp"]),
                .locationWhenInUse(purposeString: "Your location is used to help nearby people see where you are during an emergency.")
            ],
            appCategory: "public.app-category.navigation"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageModes: [.version("6")]
)
