// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Beacon",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Beacon",
            targets: ["AppModule"],
            bundleIdentifier: "com.algotyrnt.Beacon",
            teamIdentifier: "V2F9G4736H",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .location),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .bluetoothAlways(purposeString: "For offline communication."),
                .localNetwork(purposeString: "For peer discovery.", bonjourServiceTypes: ["_beacon-mesh._tcp", "_beacon-mesh._udp"]),
                .locationWhenInUse(purposeString: "Unknown Usage Description")
            ],
            appCategory: "public.app-category.navigation"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageModes: [.version("6")]
)
